### ISSUE TITLE
Folder logo

### ISSUE THREAD

**Issue by docdoxey** [doriandrn/stickyadmin#6]
Hi

I put too much photo to the top left logo. The logo is not displayed properly and prevented from using any pages. And I can not remove it.

When we want to upload a photo, upload insert is black and mask fields. A background white is better.

When we want to change the color of some elements, the choice of colors bugs and puts everything in black.

Login page : I can not display my logo on the login page

Login Page: For the login page, I can not find the button to reset my password.

add  product  woocoomerce : there is a wysiwig that does not displayed correctly for the short description

The lower left button reset does not.

You want me to be more precise and its ok.

Sorry for my English i am french

Do you want more precisions?

**Comment by docdoxey** [comment]
<img width="1239" alt="capture d ecran 2015-12-22 a 12 15 50" src="https://cloud.githubusercontent.com/assets/6715970/11954091/cfea570e-a8a5-11e5-9f2f-425b62803e85.png">

**Comment by doriandrn** [comment]
Hey docdoxey,

Thank you very much for this! :+1: 

I'm assigning all these issues above for the 1.0.6 milestone. Let's see how they turn out in the next update! 

Cheers!

**Comment by docdoxey** [comment]
Sorry but there is another things. 

We had lost our access to woocommerce in the left sidebar
If you click on the button "personnalise" in the top sidebar, > the template give a black interface.
But the most important is the logo's problem> The admin is totally down. We can't click on pages and the left sidebar menu is imcomplete.

Thanks for your job. 

Cheers

Vincent

**Comment by doriandrn** [comment]
Hey Vincent,

Thank you once again! I'm looking into all these and should be soon shorted out. May I kindly ask you what is the browser and OS you are using in the above screenshot? I'm trying to replicate the issue with the logo but I cannot seem to. About the logo, what is it's format? Is it a PNG? 

Cheers!

**Comment by docdoxey** [comment]
My brower is google chrome. And this the same on mozilla firefox.

Yes i am not sure but i think it was a png. but it was very large.

**Comment by docdoxey** [comment]
How can i reset the plugin manually ? please

When i suppress the folder sticky admin in the ftp and i reinstall him. It is the same problem.

**Comment by doriandrn** [comment]
Hey Vincent,

I'll be adding a 'Reset Options' button to the panel for this for the next update, must be really useful.

To manually reset it you need access to the database. You need to lookup for the 'wp_options' table and remove the 'sticky_options' entry from it.

I've figured where the logo issue is coming from btw and it's almost fixed! :+1: 

Best!

**Comment by docdoxey** [comment]
Thank you ;)

**Comment by doriandrn** [comment]
Closing this, the issues are fixed, of course they need further testing but we'll see from there. 1.0.6 is  coming later today. Thank you very much, Vincent!
