### ISSUE TITLE
Problem with Visual Composer

### ISSUE THREAD

**Issue by jcxtv** [doriandrn/stickyadmin#8]
The plugin makes editing a page to see the composer visual content with 50% of page width. Could you your fix it?
![20151230_042312](https://cloud.githubusercontent.com/assets/8933437/12045926/99640762-aead-11e5-99d4-0d66f519adeb.jpg)
his?

**Comment by doriandrn** [comment]
Hey jcxtv,

Thanks for bringing this to my attention! I will take care of this issue for the next update!

Cheers!
